export const HOME_ROUTE = '/'
export const ABOUT_ROUTE = '/about'
export const SERVICE_ROUTE = '/service'
export const CONTACT_ROUTE = '/contact'
export const ADMIN_ROUTE = '/admin/login'
export const LOGIN_ROUTE = '/login'
export const ADMIN_PAGE_ROUTE = '/admin/admin_page'
export const LOGIN_PAGE_ROUTE = '/login/login_page'
export const STUDENTS_ROUTE = '/admin/admin_page/students'
export const MENTORS_ROUTE = '/admin/admin_page/mentors'
export const TEAM_LEAD_ROUTE = '/admin/admin_page/team_lead'
export const ROLE_ROUTE = '/admin/admin_page/role'
export const TEAMS_ROUTE = '/admin/admin_page/get_teams'
export const COURSES_ROUTE = '/admin/admin_page/courses'

